services:
  filestash:
    image: machines/filestash:latest
    container_name: filestash
    networks:
      - vpn_net
    volumes:
    - ./config:/app/data/state
    - /mnt/doucments/:/documents
    - /mnt/storage/:/storage
    ports:
      - "8334:8334"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  vpn_net:
    external: true