services:
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - vpn_net
    restart: unless-stopped

    environment:
      POSTGRES_DB: [DB NAME]
      POSTGRES_USER: [POSTGRES_USER]
      POSTGRES_PASSWORD: [POSTGRES_PASSWORD]
      TZ: ${TZ}

    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql:ro
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh:ro


    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgresdata:

networks:
  vpn_net:
    external: true