services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf

    network_mode: "container:gluetun"

    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - ${STORAGE}:/storage

    environment:
      TZ: ${TZ}

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"