services:
  smbshare:
    image: dperson/samba:latest
    container_name: smbshare

    environment:
      TZ: ${TZ}

    volumes:
      - ${PATH}:/path:rw

    command: >
      -u "${USERNAME};${PASSWORD}"
      -s "Share;/path;yes;no;no;${USERNAME}"
      -p

    ports:
      - "139:139"
      - "445:445"

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - vpn_net

networks:
  vpn_net:
    external: true